### ISSUE TITLE
Reuse jQuery Sizzle if Present

### ISSUE THREAD

**Issue by mhemesath** [webmonarch/d34raphael#10]
If jQuery is present we can have d34raphael automatically expose it if needed. For example:

```
 if (typeof jQuery != 'undefined' && jQuery.browser.msie) {
     window.Sizzle = jQuery.find;
 }
```

This will make d34raphael slightly easier to consume for jQuery users.

**Comment by issa-tseng** [comment]
For what it's worth I implemented this at https://github.com/clint-tseng/d34raphael/commit/c7963b4a81bb56e950f3a6cf18e0ebf1a898f3f6 but due to the way you have to hook it into Raphael I'm not sure it's actually more performant.

**Comment by issa-tseng** [comment]
Merged.
