### ISSUE TITLE
Appended entered nodes not added to update selection.

### ISSUE THREAD

**Issue by mhemesath** [webmonarch/d34raphael#12]
D3 states that after a nodes is appended, it should be available in the update selection. This makes the code a lot easier when appends/updates share the same attributes, which they usually do.

```
var circle = svg.selectAll("circle")
    .data([32, 57, 293], String);

circle.enter().append("circle")
    .attr("cy", 90)
    .attr("cx", String)
    .attr("r", Math.sqrt);
```

**Comment by webmonarch** [comment]
Did you figure this out?  I believe this is implemented, but I cannot readily find an example online.

**Comment by mhemesath** [comment]
I think I misinterpreted the doc. I assumed that after doing an append, the selection would become the udpate selection. It doesn't appear to do this if you chain the calls, but it does do it if you dont. e.g.

```
circle.enter().append("circle")
circle
    .attr("cy", 90)
    .attr("cx", String)
    .attr("r", Math.sqrt);
```

**Comment by webmonarch** [comment]
Yeah, in that case, after calling data() you get an update selection.  

Elements added on enter are available in the update selection (if you have a previous reference to it).  You can alternatively call update on the enter selection to get back:

``` javascript
circle
  .enter()
    .append("circle")
  .update()
    .attr(...);
```

**Comment by mhemesath** [comment]
Hmm.. that doesn't seem to work.

**Comment by webmonarch** [comment]
I knew if I replied off the cuff, I was going to get proven wrong. :)  I cannot test from this computer, but the area of the code: https://github.com/webmonarch/d3/blob/raphael-compat/src/raphael/selection.js#L112

**Comment by mhemesath** [comment]
haha, sorry.  I didn't use **that** example.. but tried that in my existing code. It's not a huge deal for now. I'll investigate later and reopen the issue with a working example from D3 and a broken one from d34raphael if I can indeed find one.
