### ISSUE TITLE
mouse-events possible?

### ISSUE THREAD

**Issue by ThomasDeutsch** [webmonarch/d34raphael#13]
i would like to add a mouseover-event listener for my element. Is this possible?

svg.append('circle')
    .attr('cx', coordinates[0])
    .attr('cy', coordinates[1])
    .attr('r', 11)
    .attr("class", "mouseovermarkers")

```
.on("mouseover", function(){showdetails(office)});
```

**Comment by mhemesath** [comment]
I don't believe this is functionality is in the main repository yet.  @webmonarch and I have been discussing how to improve this project and merge a fork I've made https://github.com/mhemesath/d34raphael  that includes that feature with his main repository.

At the moment you can either use my fork, or issue a pull request to bring the `selection.on` functionality I've completed in my fork to this one.

**Comment by mhemesath** [comment]
The specific file you're looking for is here: https://github.com/mhemesath/d34raphael/blob/master/src/selection-on.js

**Comment by issa-tseng** [comment]
This functionality is now merged via https://github.com/webmonarch/d3/pull/4
