### ISSUE TITLE
Raphael.js as an overlay on d3.js

### ISSUE THREAD

**Issue by georgeneil** [webmonarch/d34raphael#14]
I have a scatter plot created purely using d3.js.

I am wondering whether its possible to use Raphael.js paper.path() functionality on my scatter plot so that i can draw polygons on the scatter plot. I need to track mouse click and double click on the scatter plot to set the polygon.

Is this some thing direct or should i need to redraw my scatter plot using d34raphael.js. In that case should i be able to use Raphael.js paper.path() functionality easily ?  some thing like d3.raphael.path()

**Comment by issa-tseng** [comment]
This is now very old, but if you're just building a scatter plot, I'd strongly consider building it with pure HTML elements rather than bothering with either SVG or D34Raphael; it'll be much easier to manipulate, and probably more performant too.
