### ISSUE TITLE
Package d34r as a JS library for use WITH d3.v2.js

### ISSUE THREAD

**Issue by webmonarch** [webmonarch/d34raphael#4]
Right now, d3 + d34r builds into a monolithic JS file, it should be possible to build d34r specific additions into it's own file which should be used alongside d3 js.

This is will be complicated by the fact that the d34r impl re-uses a fair bit of code from d3, so building it stand-alone isn't currently possible.

**Comment by issa-tseng** [comment]
Tracking in https://github.com/webmonarch/d34raphael/pull/9
