### ISSUE TITLE
Create as Standalone Plugin

### ISSUE THREAD

**Issue by mhemesath** [webmonarch/d34raphael#8]
I think this project would be easier to consume and understand if it were packaged as as standalone D3 plugin rather than a fork of D3 itself.  Essentially the project should just consist of everything in this directory: https://github.com/webmonarch/d3/tree/raphael-compat/src/raphael and build into a single file. 

We could then include instructions on how to consume this file, along with a custom build of D3 to get this working. I think most developers have some sort of asset build system in place that this will not be an issue.

**Comment by issa-tseng** [comment]
Tracking in https://github.com/webmonarch/d34raphael/pull/9
